version: '3.8'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      MY_SECRET: ${REDIS_API_URL}

  redis:
    image: "redis/redis-stack-server:latest"
    ports:
      - "6379:6379"